[package]
name = "poseidon"
version = "1.4.0"
edition = "2018"

[dependencies]
icicle-cuda-runtime = { path = "../../../wrappers/rust/icicle-cuda-runtime" }
icicle-core = { path = "../../../wrappers/rust/icicle-core", features = ["arkworks"] }
icicle-bls12-381 = { path = "../../../wrappers/rust/icicle-curves/icicle-bls12-381", features = ["arkworks"] }

ark-ff = { version = "0.4.0" }
ark-poly = "0.4.0"
ark-std = "0.4.0"
ark-bls12-381 = { version = "0.4.0" }
clap = { version = "<=4.4.12", features = ["derive"] }

[features]
profile = []
