// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BW6_761_API_H
#define BW6_761_API_H

#include "fields/snark_fields/bw6_761_scalar.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"

extern "C" void bw6_761GenerateScalars(bw6_761::scalar_t* scalars, int size);

extern "C" cudaError_t bw6_761ScalarConvertMontgomery(
  bw6_761::scalar_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

#endif