// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: scripts/gen_c_api.py

#pragma once
#ifndef BN254_API_H
#define BN254_API_H

#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"
#include "curves/params/bn254.cuh"
#include "ntt/ntt.cuh"
#include "msm/msm.cuh"
#include "vec_ops/vec_ops.cuh"
#include "poseidon/poseidon.cuh"
#include "poseidon/tree/merkle.cuh"
#include "poseidon2/poseidon2.cuh"

extern "C" cudaError_t bn254_g2_precompute_msm_bases_cuda(
  bn254::g2_affine_t* bases,
  int msm_size,
  msm::MSMConfig& config,
  bn254::g2_affine_t* output_bases);

extern "C" cudaError_t bn254_g2_msm_cuda(
  const bn254::scalar_t* scalars, const bn254::g2_affine_t* points, int msm_size, msm::MSMConfig& config, bn254::g2_projective_t* out);

extern "C" cudaError_t bn254_precompute_msm_bases_cuda(
  bn254::affine_t* bases,
  int msm_size,
  msm::MSMConfig& config,
  bn254::affine_t* output_bases);

extern "C" cudaError_t bn254_msm_cuda(
  const bn254::scalar_t* scalars, const bn254::affine_t* points, int msm_size, msm::MSMConfig& config, bn254::projective_t* out);

extern "C" bool bn254_g2_eq(bn254::g2_projective_t* point1, bn254::g2_projective_t* point2);

extern "C" void bn254_g2_to_affine(bn254::g2_projective_t* point, bn254::g2_affine_t* point_out);

extern "C" void bn254_g2_generate_projective_points(bn254::g2_projective_t* points, int size);

extern "C" void bn254_g2_generate_affine_points(bn254::g2_affine_t* points, int size);

extern "C" cudaError_t bn254_g2_affine_convert_montgomery(
  bn254::g2_affine_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t bn254_g2_projective_convert_montgomery(
  bn254::g2_projective_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t bn254_ecntt_cuda(
  const bn254::projective_t* input, int size, ntt::NTTDir dir, ntt::NTTConfig<bn254::scalar_t>& config, bn254::projective_t* output);

extern "C" bool bn254_eq(bn254::projective_t* point1, bn254::projective_t* point2);

extern "C" void bn254_to_affine(bn254::projective_t* point, bn254::affine_t* point_out);

extern "C" void bn254_generate_projective_points(bn254::projective_t* points, int size);

extern "C" void bn254_generate_affine_points(bn254::affine_t* points, int size);

extern "C" cudaError_t bn254_affine_convert_montgomery(
  bn254::affine_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t bn254_projective_convert_montgomery(
  bn254::projective_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t bn254_create_poseidon2_constants_cuda(
  int width,
  int alpha,
  int internal_rounds,
  int external_rounds,
  const bn254::scalar_t* round_constants,
  const bn254::scalar_t* internal_matrix_diag,
  poseidon2::MdsType mds_type,
  poseidon2::DiffusionStrategy diffusion,
  device_context::DeviceContext& ctx,
  poseidon2::Poseidon2Constants<bn254::scalar_t>* poseidon_constants);

extern "C" cudaError_t bn254_init_poseidon2_constants_cuda(
  int width,
  poseidon2::MdsType mds_type,
  poseidon2::DiffusionStrategy diffusion,
  device_context::DeviceContext& ctx,
  poseidon2::Poseidon2Constants<bn254::scalar_t>* poseidon_constants);

extern "C" cudaError_t bn254_poseidon2_hash_cuda(
  const bn254::scalar_t* input,
  bn254::scalar_t* output,
  int number_of_states,
  int width,
  const poseidon2::Poseidon2Constants<bn254::scalar_t>& constants,
  poseidon2::Poseidon2Config& config);

extern "C" cudaError_t bn254_release_poseidon2_constants_cuda(
  poseidon2::Poseidon2Constants<bn254::scalar_t>* constants,
  device_context::DeviceContext& ctx);

extern "C" cudaError_t bn254_create_optimized_poseidon_constants_cuda(
  int arity,
  int full_rounds_half,
  int partial_rounds,
  const bn254::scalar_t* constants,
  device_context::DeviceContext& ctx,
  poseidon::PoseidonConstants<bn254::scalar_t>* poseidon_constants);

extern "C" cudaError_t bn254_init_optimized_poseidon_constants_cuda(
  int arity, device_context::DeviceContext& ctx, poseidon::PoseidonConstants<bn254::scalar_t>* constants);

extern "C" cudaError_t bn254_poseidon_hash_cuda(
  bn254::scalar_t* input,
  bn254::scalar_t* output,
  int number_of_states,
  int arity,
  const poseidon::PoseidonConstants<bn254::scalar_t>& constants,
  poseidon::PoseidonConfig& config);

extern "C" cudaError_t bn254_build_poseidon_merkle_tree(
  const bn254::scalar_t* leaves,
  bn254::scalar_t* digests,
  uint32_t height,
  int arity,
  poseidon::PoseidonConstants<bn254::scalar_t>& constants,
  merkle::TreeBuilderConfig& config);

extern "C" cudaError_t bn254_mul_cuda(
  bn254::scalar_t* vec_a, bn254::scalar_t* vec_b, int n, vec_ops::VecOpsConfig& config, bn254::scalar_t* result);

extern "C" cudaError_t bn254_add_cuda(
  bn254::scalar_t* vec_a, bn254::scalar_t* vec_b, int n, vec_ops::VecOpsConfig& config, bn254::scalar_t* result);

extern "C" cudaError_t bn254_sub_cuda(
  bn254::scalar_t* vec_a, bn254::scalar_t* vec_b, int n, vec_ops::VecOpsConfig& config, bn254::scalar_t* result);

extern "C" cudaError_t bn254_transpose_matrix_cuda(
  const bn254::scalar_t* input,
  uint32_t row_size,
  uint32_t column_size,
  bn254::scalar_t* output,
  device_context::DeviceContext& ctx,
  bool on_device,
  bool is_async);

extern "C" void bn254_generate_scalars(bn254::scalar_t* scalars, int size);

extern "C" cudaError_t bn254_scalar_convert_montgomery(
  bn254::scalar_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t bn254_initialize_domain(
  bn254::scalar_t* primitive_root, device_context::DeviceContext& ctx, bool fast_twiddles_mode);

extern "C" cudaError_t bn254_ntt_cuda(
  const bn254::scalar_t* input, int size, ntt::NTTDir dir, ntt::NTTConfig<bn254::scalar_t>& config, bn254::scalar_t* output);

extern "C" cudaError_t bn254_release_domain(device_context::DeviceContext& ctx);

#endif