// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: scripts/gen_c_api.py

#pragma once
#ifndef STARK252_API_H
#define STARK252_API_H

#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"
#include "fields/stark_fields/stark252.cuh"
#include "ntt/ntt.cuh"
#include "vec_ops/vec_ops.cuh"

extern "C" cudaError_t stark252ExtensionMulCuda(
  stark252::extension_t* vec_a, stark252::extension_t* vec_b, int n, vec_ops::VecOpsConfig& config, stark252::extension_t* result);

extern "C" cudaError_t stark252ExtensionAddCuda(
  stark252::extension_t* vec_a, stark252::extension_t* vec_b, int n, vec_ops::VecOpsConfig& config, stark252::extension_t* result);

extern "C" cudaError_t stark252ExtensionSubCuda(
  stark252::extension_t* vec_a, stark252::extension_t* vec_b, int n, vec_ops::VecOpsConfig& config, stark252::extension_t* result);

extern "C" cudaError_t stark252ExtensionTransposeMatrix(
  const stark252::extension_t* input,
  uint32_t row_size,
  uint32_t column_size,
  stark252::extension_t* output,
  device_context::DeviceContext& ctx,
  bool on_device,
  bool is_async);

extern "C" cudaError_t stark252MulCuda(
  stark252::scalar_t* vec_a, stark252::scalar_t* vec_b, int n, vec_ops::VecOpsConfig& config, stark252::scalar_t* result);

extern "C" cudaError_t stark252AddCuda(
  stark252::scalar_t* vec_a, stark252::scalar_t* vec_b, int n, vec_ops::VecOpsConfig& config, stark252::scalar_t* result);

extern "C" cudaError_t stark252SubCuda(
  stark252::scalar_t* vec_a, stark252::scalar_t* vec_b, int n, vec_ops::VecOpsConfig& config, stark252::scalar_t* result);

extern "C" cudaError_t stark252TransposeMatrix(
  const stark252::scalar_t* input,
  uint32_t row_size,
  uint32_t column_size,
  stark252::scalar_t* output,
  device_context::DeviceContext& ctx,
  bool on_device,
  bool is_async);

extern "C" cudaError_t stark252ExtensionNTTCuda(
  const stark252::extension_t* input, int size, ntt::NTTDir dir, ntt::NTTConfig<stark252::scalar_t>& config, stark252::extension_t* output);

extern "C" void stark252GenerateScalars(stark252::scalar_t* scalars, int size);

extern "C" cudaError_t stark252ScalarConvertMontgomery(
  stark252::scalar_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t stark252InitializeDomain(
  stark252::scalar_t* primitive_root, device_context::DeviceContext& ctx, bool fast_twiddles_mode);

extern "C" cudaError_t stark252NTTCuda(
  const stark252::scalar_t* input, int size, ntt::NTTDir dir, ntt::NTTConfig<stark252::scalar_t>& config, stark252::scalar_t* output);

extern "C" cudaError_t stark252ReleaseDomain(device_context::DeviceContext& ctx);

#endif