// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BABYBEAR_EXT_API_H
#define BABYBEAR_EXT_API_H

#include "fields/stark_fields/babybear.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"

extern "C" void babybearExtensionGenerateScalars(babybear::extension_t* scalars, int size);

extern "C" cudaError_t babybearExtensionScalarConvertMontgomery(
  babybear::extension_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

#endif