golang:
  - wrappers/golang/**/*.go
  - wrappers/golang/**/*.h
  - wrappers/golang/**/*.tmpl
  - go.mod
rust:
  - wrappers/rust
cpp:
  - icicle/**/*.cu
  - icicle/**/*.cuh
  - icicle/**/*.cpp
  - icicle/**/*.hpp
  - icicle/**/*.c
  - icicle/**/*.h
  - icicle/CMakeLists.txt