golang:
  - wrappers/golang/**/*.go
  - wrappers/golang/**/*.h
  - wrappers/golang/**/*.tmpl
  - go.mod
  - .github/workflows/golang.yml
rust:
  - wrappers/rust/**/*
  - '!wrappers/rust/README.md'
  - .github/workflows/rust.yml
cpp:
  - icicle/**/*.cu
  - icicle/**/*.cuh
  - icicle/**/*.cpp
  - icicle/**/*.hpp
  - icicle/**/*.c
  - icicle/**/*.h
  - icicle/CMakeLists.txt
  - .github/workflows/cpp_cuda.yml
examples:
  - examples/**/*
  - .github/workflows/examples.yml
