golang:
  - wrappers/golang/**/*.go
  - wrappers/golang/**/*.h
  - wrappers/golang/**/*.tmpl
  - go.mod
  - .github/workflows/golang.yml
rust:
  - wrappers/rust_v3/**/*
  - '!wrappers/rust/README.md'
  - .github/workflows/v3_rust.yml
cpp:
  - icicle_v3/**/*.cu
  - icicle_v3/**/*.cuh
  - icicle_v3/**/*.cpp
  - icicle_v3/**/*.hpp
  - icicle_v3/**/*.c
  - icicle_v3/**/*.h
  - icicle_v3/CMakeLists.txt
  - .github/workflows/v3.yml
  - icicle_v3/cmake/curve.cmake
  - icicle_v3/cmake/field.cmake
examples:
  - examples/**/*
  - .github/workflows/examples.yml
