[package]
name = "icicle-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
icicle-runtime = { workspace = true }
hex = "0.4"
once_cell = "1.10.0" # how to have it in dev-deps?
rayon = "1.8.1"
rand = "0.8" # TODO move to dev-dependencies

[dev-dependencies]
criterion = "0.3"
serial_test = "3.0.0"
once_cell = "1.10.0"

[features]
g2 = []
ec_ntt = []
