[package]
name = "icicle-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
icicle-runtime = { workspace = true }
hex = "0.4"

[dev-dependencies]
criterion = "0.3"
serial_test = "3.0.0"
