[package]
name = "icicle-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
icicle-runtime = { workspace = true }

hex = "0.4"
