// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BLS12_377_CURVE_G2_API_H
#define BLS12_377_CURVE_G2_API_H

#include "curves/params/bls12_377.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"

extern "C" bool bls12_377G2Eq(bls12_377::g2_projective_t* point1, bls12_377::g2_projective_t* point2);

extern "C" void bls12_377G2ToAffine(bls12_377::g2_projective_t* point, bls12_377::g2_affine_t* point_out);

extern "C" void bls12_377G2GenerateProjectivePoints(bls12_377::g2_projective_t* points, int size);

extern "C" void bls12_377G2GenerateAffinePoints(bls12_377::g2_affine_t* points, int size);

extern "C" cudaError_t bls12_377G2AffineConvertMontgomery(
  bls12_377::g2_affine_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t bls12_377G2ProjectiveConvertMontgomery(
  bls12_377::g2_projective_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

#endif