// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef GRUMPKIN_POSEIDON_API_H
#define GRUMPKIN_POSEIDON_API_H

#include "fields/snark_fields/grumpkin_scalar.cuh"
#include <cuda_runtime.h>
#include "poseidon/poseidon.cuh"
#include "poseidon/tree/merkle.cuh"
#include "gpu-utils/device_context.cuh"

extern "C" cudaError_t grumpkin::PoseidonHash(
  grumpkin::scalar_t* input,
  grumpkin::scalar_t* output,
  int number_of_states,
  int arity,
  const poseidon::PoseidonConstants<grumpkin::scalar_t>& constants,
  poseidon::PoseidonConfig& config);

extern "C" cudaError_t grumpkin::BuildPoseidonMerkleTree(
  const grumpkin::scalar_t* leaves,
  grumpkin::scalar_t* digests,
  uint32_t height,
  int arity,
  poseidon::PoseidonConstants<grumpkin::scalar_t>& constants,
  merkle::TreeBuilderConfig& config);

#endif