// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BLS12_377_MSM_API_H
#define BLS12_377_MSM_API_H

#include "curves/params/bls12_377.cuh"
#include <cuda_runtime.h>
#include "msm/msm.cuh"
#include "gpu-utils/device_context.cuh"

extern "C" cudaError_t bls12_377PrecomputeMSMBases(
  bls12_377::affine_t* bases,
  int bases_size,
  int precompute_factor,
  int _c,
  bool are_bases_on_device,
  device_context::DeviceContext& ctx,
  bls12_377::affine_t* output_bases);

extern "C" cudaError_t bls12_377MSMCuda(
  const bls12_377::scalar_t* scalars, const bls12_377::affine_t* points, int msm_size, msm::MSMConfig& config, bls12_377::projective_t* out);

#endif