# Use the official NVIDIA development runtime image for Ubuntu 22.04
FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

# Install necessary packages
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \    
    tar

# Define the environment variable for the output tar file name
ENV OUTPUT_TAR_NAME=icicle30-ubuntu22-cuda122.tar.gz
