# Use the official NVIDIA development runtime image for Ubuntu 22.04
FROM nvidia/cuda:12.2.2-devel-ubuntu22.04

# Install necessary packages
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    tar
