# Use the official NVIDIA CUDA development image for CentOS 7
FROM nvidia/cuda:12.2.0-devel-centos7

# Install necessary packages
RUN yum -y update && \
    yum -y install \
    gcc \
    gcc-c++ \
    make \
    cmake \
    tar \
    && yum clean all

# Define the environment variable for the output tar file name
ENV OUTPUT_TAR_NAME=icicle30-centos7-cuda122.tar.gz