// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BW6_761_NTT_API_H
#define BW6_761_NTT_API_H

#include "fields/snark_fields/bw6_761_scalar.cuh"
#include <cuda_runtime.h>
#include "ntt/ntt.cuh"
#include "gpu-utils/device_context.cuh"

extern "C" cudaError_t bw6_761InitializeDomain(
  bw6_761::scalar_t* primitive_root, device_context::DeviceContext& ctx, bool fast_twiddles_mode);

extern "C" cudaError_t bw6_761NTTCuda(
  const bw6_761::scalar_t* input, int size, NTTDir dir, ntt::NTTConfig<bw6_761::scalar_t>& config, bw6_761::scalar_t* output)

extern "C" cudaError_t bw6_761ReleaseDomain(device_context::DeviceContext& ctx);

#endif