// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BLS12_377_ECNTT_API_H
#define BLS12_377_ECNTT_API_H

#include "curves/params/bls12_377.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"
#include "ntt/ntt.cuh"

extern "C" cudaError_t bls12_377ECNTTCuda(
  const bls12_377::projective_t* input, int size, NTTDir dir, ntt::NTTConfig<bls12_377::scalar_t>& config, bls12_377::projective_t* output);

#endif