#pragma once

#include "icicle/math/storage.h"
#include "icicle/rings/integer_ring.h"
#include "icicle/fields/params_gen.h"

// RNS
#include "icicle/rings/integer_ring_rns.h"
#include "icicle/fields/stark_fields/babybear.h"
#include "icicle/fields/stark_fields/koalabear.h"

namespace labrador {
  // Zq such that q = Pbb*Pkb for Pbb,Pkb the primes of baby-bear and koala-bear fields
  struct zq_config {
    static constexpr storage<2> modulus = {0xf7000001, 0x3b880000};
    PARAMS(modulus);

    static constexpr storage<2> rou = {0x8be440ed, 0x0309b111};
    static constexpr unsigned omegas_count = 24;
    static constexpr storage_array<omegas_count, limbs_count> inv =
      params_gen::template get_invs<limbs_count, omegas_count>(modulus);
  };

  /**
   *  Define the integer ring Zq
   */
  using Zq = IntegerRing<zq_config>;
  using scalar_t = Zq;

  struct zq_rns_config {
    using Fields = std::tuple<babybear::scalar_t, koalabear::scalar_t>;
    static constexpr unsigned limbs_count = 2;
    // Offset in limbs_storage for each field
    static constexpr std::array<unsigned, 2> FieldOffset = {0, 1};
    static constexpr size_t omegas_count = 24;

    // Auto-generated by scripts/python/integer_ring.py
    // W are the precomputed values for the CRT
    static constexpr storage_array<2, 2> W = {storage<2>{0x30924914, 0x22049241}, storage<2>{0xc66db6ee, 0x19836dbf}};
    using Zq = IntegerRing<zq_config>;
    ;
  };

  /**
   *  Define the integer ring ZqRns
   */
  using scalar_rns_t = IntegerRingRns<zq_rns_config>;

} // namespace labrador