// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BN254_CURVE_API_H
#define BN254_CURVE_API_H

#include "curves/params/bn254.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"

extern "C" bool bn254Eq(bn254::projective_t* point1, bn254::projective_t* point2);

extern "C" void bn254ToAffine(bn254::projective_t* point, bn254::affine_t* point_out);

extern "C" void bn254GenerateProjectivePoints(bn254::projective_t* points, int size);

extern "C" void bn254GenerateAffinePoints(bn254::affine_t* points, int size);

extern "C" cudaError_t bn254AffineConvertMontgomery(
  bn254::affine_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t bn254ProjectiveConvertMontgomery(
  bn254::projective_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx)

#endif