// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BN254_CURVE_G2_API_H
#define BN254_CURVE_G2_API_H

#include "curves/params/bn254.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"

extern "C" bool bn254G2Eq(bn254::g2_projective_t* point1, bn254::g2_projective_t* point2);

extern "C" void bn254G2ToAffine(bn254::g2_projective_t* point, bn254::g2_affine_t* point_out);

extern "C" void bn254G2GenerateProjectivePoints(bn254::g2_projective_t* points, int size);

extern "C" void bn254G2GenerateAffinePoints(bn254::g2_affine_t* points, int size);

extern "C" cudaError_t bn254G2AffineConvertMontgomery(
  bn254::g2_affine_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t bn254G2ProjectiveConvertMontgomery(
  bn254::g2_projective_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

#endif