// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BW6_761_ECNTT_API_H
#define BW6_761_ECNTT_API_H

#include "curves/params/bw6_761.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"
#include "ntt/ntt.cuh"

extern "C" cudaError_t bw6_761ECNTTCuda(
  const bw6_761::projective_t* input, int size, NTTDir dir, ntt::NTTConfig<bw6_761::scalar_t>& config, bw6_761::projective_t* output);

#endif