// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BLS12_377_EXT_API_H
#define BLS12_377_EXT_API_H

#include "fields/snark_fields/bls12_377_scalar.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"

extern "C" void bls12_377ExtensionGenerateScalars(bls12_377::extension_t* scalars, int size);

extern "C" cudaError_t bls12_377ExtensionScalarConvertMontgomery(
  bls12_377::extension_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

#endif