test_blake2s: test_blake2s.cu blake2s.cu 
	nvcc -o test_blake2s -I. -I../../../include test_blake2s.cu blake2s.cu -g

test_blake2s_hasher: test_blake2s_hasher.cu blake2s.cu 
	nvcc -o test_blake2s_hasher -I. -I../../../include test_blake2s_hasher.cu -g