
	// Copyright 2023 Ingonyama
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//     http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	
// Code generated by Ingonyama DO NOT EDIT

package bls12377

import (
	"encoding/binary"
	"fmt"
	"testing"

	


	"github.com/consensys/gnark-crypto/ecc/bls12-377"



	

	"github.com/consensys/gnark-crypto/ecc/bls12-377/fp"



	


	"github.com/consensys/gnark-crypto/ecc/bls12-377/fr"



	"github.com/stretchr/testify/assert"
)

func TestNewFieldBLS12377One(t *testing.T) {
	oneField := NewBaseFieldOne()
	rawOneField := [8]uint32([8]uint32{0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0})

	assert.Equal(t, oneField.s, rawOneField)
}

func TestNewFieldBLS12377Zero(t *testing.T) {
	zeroField := NewFieldZero[BaseField]()
	rawZeroField := [8]uint32([8]uint32{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0})

	assert.Equal(t, zeroField.s, rawZeroField)
}

func TestFieldBLS12377FromGnark(t *testing.T) {
	var rand fr.Element
	rand.SetRandom()

	f := NewFieldFromFrGnark[ScalarField](rand)

	assert.Equal(t, f.s, ConvertUint64ArrToUint32Arr4(rand.Bits()))
}

func BenchmarkBatchConvertFromFrGnarkThreaded(b *testing.B) {
	// ROUTINES := []int{4,5,6,7,8}

	// for _, routineAmount := range ROUTINES {
	routineAmount := 7
	_, scalars_fr := GenerateScalars(1 << 24, false)
	b.Run(fmt.Sprintf("Convert %d", routineAmount), func(b *testing.B) {
		for n := 0; n < b.N; n++ {
			_ = BatchConvertFromFrGnarkThreaded[ScalarField](scalars_fr, routineAmount)
		}
	})
	// }
}

func BenchmarkBatchConvertFromFrGnark(b *testing.B) {
	_, scalars_fr := GenerateScalars(1 << 24, false)
	b.Run("BatchConvert 2^24", func(b *testing.B) {
		for n := 0; n < b.N; n++ {
			_ = BatchConvertFromFrGnark[ScalarField](scalars_fr)
		}
	})
}

func TestFieldBLS12377ToBytesLe(t *testing.T) {
	var rand fr.Element
	rand.SetRandom()

	f := NewFieldFromFrGnark[ScalarField](rand)

	expected := make([]byte, len(f.s)*4) // each uint32 takes 4 bytes
	for i, v := range f.s {
		binary.LittleEndian.PutUint32(expected[i*4:], v)
	}

	assert.Equal(t, f.toBytesLe(), expected)
	assert.Equal(t, len(f.toBytesLe()), 32)
}

func TestNewPointBLS12377Zero(t *testing.T) {
	point := NewPointBLS12377Zero()
	a := new(PointBLS12377)
	a.ToGnarkJac()

	assert.Equal(t, point.x, *NewFieldZero[BaseField]())
	assert.Equal(t, point.y, *NewBaseFieldOne())
	assert.Equal(t, point.z, *NewFieldZero[BaseField]())
}

func TestBLS12377Eq(t *testing.T) {
	p1 := NewPointBLS12377Zero()
	p2 := NewPointBLS12377Zero()
	p3 := &PointBLS12377{
		x: *NewBaseFieldOne(),
		y: *NewBaseFieldOne(),
		z: *NewBaseFieldOne(),
	}

	assert.Equal(t, p1.eq(p2), true)
	assert.Equal(t, p1.eq(p3), false)
}

func TestBLS12377StripZ(t *testing.T) {
	p1 := NewPointBLS12377Zero()
	p2ZLess := p1.strip_z()

	assert.IsType(t, PointAffineNoInfinityBLS12377{}, *p2ZLess)
	assert.Equal(t, p1.x, p2ZLess.x)
	assert.Equal(t, p1.y, p2ZLess.y)
}

func TestPointBLS12377FromGnark(t *testing.T) {
	gnarkP, _ := randG1Jac()

	p := PointBLS12377FromJacGnark(&gnarkP)

	z_inv := new(fp.Element)
	z_invsq := new(fp.Element)
	z_invq3 := new(fp.Element)
	x := new(fp.Element)
	y := new(fp.Element)

	z_inv.Inverse(&gnarkP.Z)
	z_invsq.Mul(z_inv, z_inv)
	z_invq3.Mul(z_invsq, z_inv)

	x.Mul(&gnarkP.X, z_invsq)
	y.Mul(&gnarkP.Y, z_invq3)

	assert.Equal(t, p.x, *NewFieldFromFpGnark[BaseField](*x))
	assert.Equal(t, p.y, *NewFieldFromFpGnark[BaseField](*y))
	assert.Equal(t, p.z, *NewBaseFieldOne())
}

func TestPointBLS12377fromLimbs(t *testing.T) {
	gnarkP, _ := randG1Jac()
	p := PointBLS12377FromJacGnark(&gnarkP)

	x := p.x.limbs()
	y := p.y.limbs()
	z := p.z.limbs()

	xSlice := x[:]
	ySlice := y[:]
	zSlice := z[:]

	pFromLimbs := PointBLS12377fromLimbs(&xSlice, &ySlice, &zSlice)

	assert.Equal(t, pFromLimbs, p)
}

func TestNewPointAffineNoInfinityBLS12377Zero(t *testing.T) {
	zeroP := NewPointAffineNoInfinityBLS12377Zero()

	assert.Equal(t, zeroP.x, *NewFieldZero[BaseField]())
	assert.Equal(t, zeroP.y, *NewFieldZero[BaseField]())
}

func TestPointAffineNoInfinityBLS12377ToProjective(t *testing.T) {
	gnarkP, _ := randG1Jac()
	affine := PointBLS12377FromJacGnark(&gnarkP).strip_z()
	proj := affine.toProjective()

	assert.Equal(t, proj.x, affine.x)
	assert.Equal(t, proj.x, affine.x)
	assert.Equal(t, proj.z, *NewBaseFieldOne())
}

func TestPointAffineNoInfinityBLS12377FromLimbs(t *testing.T) {
	// Initialize your test values
	x := []uint32{1, 2, 3, 4, 5, 6, 7, 8}
	y := []uint32{9, 10, 11, 12, 13, 14, 15, 16}

	// Execute your function
	result := PointAffineNoInfinityBLS12377FromLimbs(&x, &y)

	// Define your expected result
	expected := &PointAffineNoInfinityBLS12377{
		x: *BaseFieldFromLimbs(getFixedLimbs(&x)),
		y: *BaseFieldFromLimbs(getFixedLimbs(&y)),
	}

	// Test if result is as expected
	assert.Equal(t, result, expected)
}

func TestToGnarkAffine(t *testing.T) {
	gJac, _ := randG1Jac()
	proj := PointBLS12377FromJacGnark(&gJac)

	var gAffine bls12377.G1Affine
	gAffine.FromJacobian(&gJac)

	affine := *proj.toGnarkAffine()
	assert.Equal(t, affine, gAffine)
}

func TestGetFixedLimbs(t *testing.T) {
	t.Run("case of valid input of length less than 8", func(t *testing.T) {
		slice := []uint32{1, 2, 3, 4, 5, 6, 7}
		expected := [8]uint32{1, 2, 3, 4, 5, 6, 7, 0}

		result := getFixedLimbs(&slice)
		assert.Equal(t, result, expected)
	})

	t.Run("case of valid input of length 8", func(t *testing.T) {
		slice := []uint32{1, 2, 3, 4, 5, 6, 7, 8}
		expected := [8]uint32{1, 2, 3, 4, 5, 6, 7, 8}

		result := getFixedLimbs(&slice)
		assert.Equal(t, result, expected)
	})

	t.Run("case of empty input", func(t *testing.T) {
		slice := []uint32{}
		expected := [8]uint32{0, 0, 0, 0, 0, 0, 0, 0}

		result := getFixedLimbs(&slice)
		assert.Equal(t, result, expected)
	})

	t.Run("case of input length greater than 8", func(t *testing.T) {
		slice := []uint32{1, 2, 3, 4, 5, 6, 7, 8, 9}

		defer func() {
			if r := recover(); r == nil {
				t.Errorf("the code did not panic")
			}
		}()

		getFixedLimbs(&slice)
	})
}
