
	// Copyright 2023 Ingonyama
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//     http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	
// Code generated by Ingonyama DO NOT EDIT

package bls12381

import (
	"fmt"
	"reflect"
	"testing"

	


	"github.com/consensys/gnark-crypto/ecc/bls12-381/fr"



	


	"github.com/consensys/gnark-crypto/ecc/bls12-381/fr/fft"



	"github.com/stretchr/testify/assert"
)

func TestNttBLS12381BBB(t *testing.T) {
	count := 1 << 20
	scalars, frScalars := GenerateScalars(count, false)

	nttResult := make([]ScalarField, len(scalars)) // Make a new slice with the same length
	copy(nttResult, scalars)

	assert.Equal(t, nttResult, scalars)
	NttBatchBLS12381(&nttResult, false, count, 0)
	assert.NotEqual(t, nttResult, scalars)

	domain := fft.NewDomain(uint64(len(scalars)))
	// DIT WITH NO INVERSE
	// DIF WITH INVERSE
	domain.FFT(frScalars, fft.DIT) //DIF

	nttResultTransformedToGnark := make([]fr.Element, len(scalars)) // Make a new slice with the same length

	for k, v := range nttResult {
		nttResultTransformedToGnark[k] = *v.ToGnarkFr()
	}

	assert.Equal(t, nttResultTransformedToGnark, frScalars)
}

func TestNttBLS12381CompareToGnarkDIF(t *testing.T) {
	count := 1 << 2
	scalars, frScalars := GenerateScalars(count, false)

	nttResult := make([]ScalarField, len(scalars)) // Make a new slice with the same length
	copy(nttResult, scalars)

	assert.Equal(t, nttResult, scalars)
	NttBLS12381(&nttResult, false, DIF, 0)
	assert.NotEqual(t, nttResult, scalars)

	domain := fft.NewDomain(uint64(len(scalars)))
	// DIT WITH NO INVERSE
	// DIF WITH INVERSE
	domain.FFT(frScalars, fft.DIF) //DIF

	nttResultTransformedToGnark := make([]fr.Element, len(scalars)) // Make a new slice with the same length

	for k, v := range nttResult {
		nttResultTransformedToGnark[k] = *v.ToGnarkFr()
	}

	assert.Equal(t, nttResultTransformedToGnark, frScalars)
}

func TestNttBLS12381CompareToGnarkDIT(t *testing.T) {
	count := 1 << 2
	scalars, frScalars := GenerateScalars(count, false)

	nttResult := make([]ScalarField, len(scalars)) // Make a new slice with the same length
	copy(nttResult, scalars)

	assert.Equal(t, nttResult, scalars)
	NttBLS12381(&nttResult, false, DIT, 0)
	assert.NotEqual(t, nttResult, scalars)

	domain := fft.NewDomain(uint64(len(scalars)))
	// DIT WITH NO INVERSE
	// DIF WITH INVERSE
	domain.FFT(frScalars, fft.DIT) //DIF

	nttResultTransformedToGnark := make([]fr.Element, len(scalars)) // Make a new slice with the same length

	for k, v := range nttResult {
		nttResultTransformedToGnark[k] = *v.ToGnarkFr()
	}

	assert.Equal(t, nttResultTransformedToGnark, frScalars)
}

func TestINttBLS12381CompareToGnarkDIT(t *testing.T) {
	count := 1 << 3
	scalars, frScalars := GenerateScalars(count, false)

	nttResult := make([]ScalarField, len(scalars)) // Make a new slice with the same length
	copy(nttResult, scalars)

	assert.Equal(t, nttResult, scalars)
	NttBLS12381(&nttResult, true, DIT, 0)
	assert.NotEqual(t, nttResult, scalars)

	frResScalars := make([]fr.Element, len(frScalars)) // Make a new slice with the same length
	copy(frResScalars, frScalars)

	domain := fft.NewDomain(uint64(len(scalars)))
	domain.FFTInverse(frResScalars, fft.DIT)

	assert.NotEqual(t, frResScalars, frScalars)

	nttResultTransformedToGnark := make([]fr.Element, len(scalars)) // Make a new slice with the same length

	for k, v := range nttResult {
		nttResultTransformedToGnark[k] = *v.ToGnarkFr()
	}

	assert.Equal(t, nttResultTransformedToGnark, frResScalars)
}

func TestINttBLS12381CompareToGnarkDIF(t *testing.T) {
	count := 1 << 3
	scalars, frScalars := GenerateScalars(count, false)

	nttResult := make([]ScalarField, len(scalars)) // Make a new slice with the same length
	copy(nttResult, scalars)

	assert.Equal(t, nttResult, scalars)
	NttBLS12381(&nttResult, true, DIF, 0)
	assert.NotEqual(t, nttResult, scalars)

	domain := fft.NewDomain(uint64(len(scalars)))
	domain.FFTInverse(frScalars, fft.DIF)

	nttResultTransformedToGnark := make([]fr.Element, len(scalars)) // Make a new slice with the same length

	for k, v := range nttResult {
		nttResultTransformedToGnark[k] = *v.ToGnarkFr()
	}

	assert.Equal(t, nttResultTransformedToGnark, frScalars)
}

func TestNttBLS12381(t *testing.T) {
	count := 1 << 3

	scalars, _ := GenerateScalars(count, false)

	nttResult := make([]ScalarField, len(scalars)) // Make a new slice with the same length
	copy(nttResult, scalars)

	assert.Equal(t, nttResult, scalars)
	NttBLS12381(&nttResult, false, NONE, 0)
	assert.NotEqual(t, nttResult, scalars)

	inttResult := make([]ScalarField, len(nttResult))
	copy(inttResult, nttResult)

	assert.Equal(t, inttResult, nttResult)
	NttBLS12381(&inttResult, true, NONE, 0)
	assert.Equal(t, inttResult, scalars)
}

func TestNttBatchBLS12381(t *testing.T) {
	count := 1 << 5
	batches := 4

	scalars, _ := GenerateScalars(count * batches, false)

	var scalarVecOfVec [][]ScalarField = make([][]ScalarField, 0)

	for i := 0; i < batches; i++ {
		start := i * count
		end := (i + 1) * count
		batch := make([]ScalarField, len(scalars[start:end]))
		copy(batch, scalars[start:end])
		scalarVecOfVec = append(scalarVecOfVec, batch)
	}

	nttBatchResult := make([]ScalarField, len(scalars))
	copy(nttBatchResult, scalars)

	NttBatchBLS12381(&nttBatchResult, false, count, 0)

	var nttResultVecOfVec [][]ScalarField

	for i := 0; i < batches; i++ {
		// Clone the slice
		clone := make([]ScalarField, len(scalarVecOfVec[i]))
		copy(clone, scalarVecOfVec[i])

		// Add it to the result vector of vectors
		nttResultVecOfVec = append(nttResultVecOfVec, clone)

		// Call the ntt_bls12381 function
		NttBLS12381(&nttResultVecOfVec[i], false, NONE, 0)
	}

	assert.NotEqual(t, nttBatchResult, scalars)

	// Check that the ntt of each vec of scalars is equal to the intt of the specific batch
	for i := 0; i < batches; i++ {
		if !reflect.DeepEqual(nttResultVecOfVec[i], nttBatchResult[i*count:((i+1)*count)]) {
			t.Errorf("ntt of vec of scalars not equal to intt of specific batch")
		}
	}
}

func BenchmarkNTT(b *testing.B) {
	LOG_NTT_SIZES := []int{12, 15, 20, 21, 22, 23, 24, 25, 26}

	for _, logNTTSize := range LOG_NTT_SIZES {
		nttSize := 1 << logNTTSize
		b.Run(fmt.Sprintf("NTT %d", logNTTSize), func(b *testing.B) {
			scalars, _ := GenerateScalars(nttSize, false)

			nttResult := make([]ScalarField, len(scalars)) // Make a new slice with the same length
			copy(nttResult, scalars)
			for n := 0; n < b.N; n++ {
				NttBLS12381(&nttResult, false, NONE, 0)
			}
		})
	}
}
