// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BLS12_381_CURVE_API_H
#define BLS12_381_CURVE_API_H

#include "curves/params/bls12_381.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"

extern "C" bool bls12_381Eq(bls12_381::projective_t* point1, bls12_381::projective_t* point2);

extern "C" void bls12_381ToAffine(bls12_381::projective_t* point, bls12_381::affine_t* point_out);

extern "C" void bls12_381GenerateProjectivePoints(bls12_381::projective_t* points, int size);

extern "C" void bls12_381GenerateAffinePoints(bls12_381::affine_t* points, int size);

extern "C" cudaError_t bls12_381AffineConvertMontgomery(
  bls12_381::affine_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t bls12_381ProjectiveConvertMontgomery(
  bls12_381::projective_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx)

#endif