use icicle_cuda_runtime::{device_context::DeviceContext, error::CudaResult};
use std::os::raw::c_int;

use crate::traits::FieldImpl;

pub mod tests;

/**
 * @enum Ordering
 * How to order inputs and outputs of the NTT. If needed, use this field to specify decimation: decimation in time
 * (DIT) corresponds to `Ordering::kRN` while decimation in frequency (DIF) to `Ordering::kNR`. Also, to specify
 * butterfly to be used, select `Ordering::kRN` for Cooley-Tukey and `Ordering::kNR` for Gentleman-Sande. There's
 * no implication that a certain decimation or butterfly will actually be used under the hood, this is just for
 * compatibility with codebases that use "decimation" and "butterfly" to denote ordering of inputs and outputs.
 *
 * Ordering options are:
 * - kNN: inputs and outputs are natural-order (example of natural ordering: \f$ \{a_0, a_1, a_2, a_3, a_4, a_5, a_6,
 * a_7\} \f$).
 * - kNR: inputs are natural-order and outputs are bit-reversed-order (example of bit-reversed ordering: \f$ \{a_0,
 * a_4, a_2, a_6, a_1, a_5, a_3, a_7\} \f$).
 * - kRN: inputs are bit-reversed-order and outputs are natural-order.
 * - kRR: inputs and outputs are bit-reversed-order.
 */
#[allow(non_camel_case_types)]
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Ordering {
    kNN,
    kNR,
    kRN,
    kRR,
}

/**
 * @struct NTTConfig
 * Struct that encodes NTT parameters to be passed into the [ntt](@ref ntt) function.
 */
#[repr(C)]
#[derive(Debug)]
pub struct NTTConfig<'a, S> {
    /** Coset generator. Used to perform coset (i)NTTs. Default value: `S::one()` (corresponding to no coset being used). */
    pub coset_gen: S,
    /** Ordering of inputs and outputs. See [Ordering](@ref Ordering). Default value: `Ordering::kNN`. */
    pub ordering: Ordering,
    /** True if inputs are on device and false if they're on host. Default value: false. */
    pub are_inputs_on_device: bool,
    /** If true, output is preserved on device for subsequent use in config and not freed after calculation. Default value: false. */
    pub are_outputs_on_device: bool,
    /** The number of NTTs to compute. Default value: 1. */
    pub batch_size: c_int,
    /** Whether to run the NTT asyncronously. If set to `true`, the NTT function will be non-blocking and you'd need to synchronize
     *  it explicitly by running `cudaStreamSynchronize` or `cudaDeviceSynchronize`. If set to false, the NTT
     *  function will block the current CPU thread. */
    pub is_async: bool,
    /** Details related to the device such as its id and stream id. See [DeviceContext](@ref device_context::DeviceContext). */
    pub ctx: DeviceContext<'a>,
}

// /**
//  * @struct Domain
//  * Struct containing information about the domain on which (i)NTT is evaluated: twiddle factors and coset generator.
//  * Twiddle factors are private, static and can only be set using [GenerateDomain](@ref GenerateDomain) function.
//  * The internal representation of twiddles is prone to change in accordance with changing [NTT](@ref NTT) algorithm.
//  */
// #[repr(C)]
// #[derive(Debug)]
// pub struct Domain<'a, T> {
//     /** Scalar elements that specify a coset to be used in (i)NTT. Default value: None (no coset or alternatively coset
//      *  generated by `S::one()` is used). */
//     pub coset_table: Option<&'a [T]>,
// }

pub trait NTT<F: FieldImpl> {
    fn ntt(input: &[F], is_inverse: bool, cfg: &NTTConfig<F>, output: &mut [F]) -> CudaResult<()>;
    fn initialize_domain(primitive_root: F, ctx: &DeviceContext) -> CudaResult<()>;
    fn get_default_ntt_config() -> NTTConfig<'static, F>;
}

#[macro_export]
macro_rules! impl_ntt {
    (
      $field_prefix:literal,
      $field:ident,
      $field_config:ident
    ) => {
        extern "C" {
            #[link_name = concat!($field_prefix, "NTTCuda")]
            fn ntt_cuda<'a>(
                input: *const $field,
                size: usize,
                is_inverse: bool,
                config: &NTTConfig<'a, $field>,
                output: *mut $field,
            ) -> CudaError;

            #[link_name = concat!($field_prefix, "DefaultNTTConfig")]
            fn default_ntt_config() -> NTTConfig<'static, $field>;

            #[link_name = concat!($field_prefix, "InitializeDomain")]
            fn initialize_ntt_domain(primitive_root: $field, ctx: &DeviceContext) -> CudaError;
        }

        impl NTT<$field> for $field_config {
            fn ntt(
                input: &[$field],
                is_inverse: bool,
                cfg: &NTTConfig<$field>,
                output: &mut [$field],
            ) -> CudaResult<()> {
                if input.len() != output.len() {
                    return Err(CudaError::cudaErrorInvalidValue);
                }

                unsafe {
                    ntt_cuda(
                        input as *const _ as *const $field,
                        input.len(),
                        is_inverse,
                        cfg,
                        output as *mut _ as *mut $field,
                    )
                    .wrap()
                }
            }

            fn initialize_domain(primitive_root: $field, ctx: &DeviceContext) -> CudaResult<()> {
                unsafe { initialize_ntt_domain(primitive_root, ctx).wrap() }
            }

            fn get_default_ntt_config() -> NTTConfig<'static, $field> {
                unsafe { default_ntt_config() }
            }
        }
    };
}

#[macro_export]
macro_rules! impl_ntt_tests {
    (
      $field:ident,
      $field_config:ident
    ) => {
        #[test]
        fn test_ntt() {
            check_ntt::<$field, $field_config>()
        }

        #[test]
        fn test_ntt_coset_from_subgroup() {
            check_ntt_coset_from_subgroup::<$field, $field_config>()
        }
    };
}
