// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BABYBEAR_NTT_EXT_API_H
#define BABYBEAR_NTT_EXT_API_H

#include "fields/stark_fields/babybear.cuh"
#include <cuda_runtime.h>
#include "ntt/ntt.cuh"
#include "gpu-utils/device_context.cuh"

extern "C" cudaError_t babybearExtensionNTTCuda(
  const babybear::extension_t* input, int size, NTTDir dir, ntt::NTTConfig<babybear::scalar_t>& config, babybear::extension_t* output)

#endif