// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef GRUMPKIN_ECNTT_API_H
#define GRUMPKIN_ECNTT_API_H

#include "curves/params/grumpkin.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"
#include "ntt/ntt.cuh"

extern "C" cudaError_t grumpkinECNTTCuda(
  const grumpkin::projective_t* input, int size, NTTDir dir, ntt::NTTConfig<grumpkin::scalar_t>& config, grumpkin::projective_t* output);

#endif