// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef GRUMPKIN_MSM_API_H
#define GRUMPKIN_MSM_API_H

#include "curves/params/grumpkin.cuh"
#include <cuda_runtime.h>
#include "msm/msm.cuh"
#include "gpu-utils/device_context.cuh"

extern "C" cudaError_t grumpkinPrecomputeMSMBases(
  grumpkin::affine_t* bases,
  int bases_size,
  int precompute_factor,
  int _c,
  bool are_bases_on_device,
  device_context::DeviceContext& ctx,
  grumpkin::affine_t* output_bases);

extern "C" cudaError_t grumpkinMSMCuda(
  const grumpkin::scalar_t* scalars, const grumpkin::affine_t* points, int msm_size, msm::MSMConfig& config, grumpkin::projective_t* out);

#endif