// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef GRUMPKIN_CURVE_API_H
#define GRUMPKIN_CURVE_API_H

#include "curves/params/grumpkin.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"

extern "C" bool grumpkinEq(grumpkin::projective_t* point1, grumpkin::projective_t* point2);

extern "C" void grumpkinToAffine(grumpkin::projective_t* point, grumpkin::affine_t* point_out);

extern "C" void grumpkinGenerateProjectivePoints(grumpkin::projective_t* points, int size);

extern "C" void grumpkinGenerateAffinePoints(grumpkin::affine_t* points, int size);

extern "C" cudaError_t grumpkinAffineConvertMontgomery(
  grumpkin::affine_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t grumpkinProjectiveConvertMontgomery(
  grumpkin::projective_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx)

#endif