// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BN254_NTT_API_H
#define BN254_NTT_API_H

#include "fields/snark_fields/bn254_scalar.cuh"
#include <cuda_runtime.h>
#include "ntt/ntt.cuh"
#include "gpu-utils/device_context.cuh"

extern "C" cudaError_t bn254InitializeDomain(
  bn254::scalar_t* primitive_root, device_context::DeviceContext& ctx, bool fast_twiddles_mode);

extern "C" cudaError_t bn254NTTCuda(
  const bn254::scalar_t* input, int size, NTTDir dir, ntt::NTTConfig<bn254::scalar_t>& config, bn254::scalar_t* output)

extern "C" cudaError_t bn254ReleaseDomain(device_context::DeviceContext& ctx);

#endif