// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BN254_NTT_EXT_API_H
#define BN254_NTT_EXT_API_H

#include "fields/snark_fields/bn254_scalar.cuh"
#include <cuda_runtime.h>
#include "ntt/ntt.cuh"
#include "gpu-utils/device_context.cuh"

extern "C" cudaError_t bn254ExtensionNTTCuda(
  const bn254::extension_t* input, int size, NTTDir dir, ntt::NTTConfig<bn254::scalar_t>& config, bn254::extension_t* output)

#endif