// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BN254_ECNTT_API_H
#define BN254_ECNTT_API_H

#include "curves/params/bn254.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"
#include "ntt/ntt.cuh"

extern "C" cudaError_t bn254ECNTTCuda(
  const bn254::projective_t* input, int size, NTTDir dir, ntt::NTTConfig<bn254::scalar_t>& config, bn254::projective_t* output);

#endif