// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BW6_761_POSEIDON_API_H
#define BW6_761_POSEIDON_API_H

#include "fields/snark_fields/bw6_761_scalar.cuh"
#include <cuda_runtime.h>
#include "poseidon/poseidon.cuh"
#include "poseidon/tree/merkle.cuh"
#include "gpu-utils/device_context.cuh"

extern "C" cudaError_t bw6_761::PoseidonHash(
  bw6_761::scalar_t* input,
  bw6_761::scalar_t* output,
  int number_of_states,
  int arity,
  const poseidon::PoseidonConstants<bw6_761::scalar_t>& constants,
  poseidon::PoseidonConfig& config);

extern "C" cudaError_t bw6_761::BuildPoseidonMerkleTree(
  const bw6_761::scalar_t* leaves,
  bw6_761::scalar_t* digests,
  uint32_t height,
  int arity,
  poseidon::PoseidonConstants<bw6_761::scalar_t>& constants,
  merkle::TreeBuilderConfig& config);

#endif