// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BW6_761_CURVE_API_H
#define BW6_761_CURVE_API_H

#include "curves/params/bw6_761.cuh"
#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"

extern "C" bool bw6_761Eq(bw6_761::projective_t* point1, bw6_761::projective_t* point2);

extern "C" void bw6_761ToAffine(bw6_761::projective_t* point, bw6_761::affine_t* point_out);

extern "C" void bw6_761GenerateProjectivePoints(bw6_761::projective_t* points, int size);

extern "C" void bw6_761GenerateAffinePoints(bw6_761::affine_t* points, int size);

extern "C" cudaError_t bw6_761AffineConvertMontgomery(
  bw6_761::affine_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t bw6_761ProjectiveConvertMontgomery(
  bw6_761::projective_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx)

#endif