[package]
name = "sumcheck"
version = "0.1.0"
edition = "2018"

[dependencies]
icicle-runtime = { path = "../../../wrappers/rust/icicle-runtime" }
icicle-core = { path = "../../../wrappers/rust/icicle-core" }
icicle-bn254 = { path = "../../../wrappers/rust/icicle-curves/icicle-bn254" }
icicle-hash = { path = "../../../wrappers/rust/icicle-hash" }


merlin = {version = "3.0.0"}
log = "0.4.25"
env_logger = "0.11.6"
clap = { version = "<=4.4.12", features = ["derive"] }

[features]
cuda = [
        "icicle-runtime/cuda_backend",
        "icicle-bn254/cuda_backend",
        "icicle-hash/cuda_backend"
]

metal = [
         "icicle-runtime/metal_backend",
        "icicle-bn254/metal_backend",
        "icicle-hash/metal_backend"
]

vulkan = [
        "icicle-runtime/vulkan_backend",
        "icicle-bn254/vulkan_backend",
        "icicle-hash/vulkan_backend"
]