[package]
name = "icicle-bn254"
version = "0.1.0"
edition = "2021"
authors = [ "Ingonyama" ]
description = "An implementation of the BN254 Pairing Ingonyama CUDA Library"
homepage = "https://www.ingonyama.com"
repository = "https://github.com/ingonyama-zk/icicle"

[dependencies]
icicle-core = { path = "../icicle-core" }
icicle-cuda-runtime = { path = "../icicle-cuda-runtime" }
ark-bn254 = { version = "0.4.0", optional = true }

[build-dependencies]
cmake = "*"

[dev-dependencies]
rand = "*" #TODO: move rand and ark dependencies to dev once random scalar/point generation is done "natively"

ark-bn254 = "0.4.0"
ark-std = "0.4.0"
ark-ff = "0.4.0"
ark-ec = "0.4.0"
ark-poly = "0.4.0"
icicle-core = { path = "../icicle-core", features = ["arkworks"] }
icicle-bn254 = { path = ".", features = ["arkworks"] }

[features]
default = []
arkworks = ["ark-bn254", "icicle-core/arkworks"]
