// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BLS12_381_POSEIDON_API_H
#define BLS12_381_POSEIDON_API_H

#include "fields/snark_fields/bls12_381_scalar.cuh"
#include <cuda_runtime.h>
#include "poseidon/poseidon.cuh"
#include "poseidon/tree/merkle.cuh"
#include "gpu-utils/device_context.cuh"

extern "C" cudaError_t bls12_381::PoseidonHash(
  bls12_381::scalar_t* input,
  bls12_381::scalar_t* output,
  int number_of_states,
  int arity,
  const poseidon::PoseidonConstants<bls12_381::scalar_t>& constants,
  poseidon::PoseidonConfig& config);

extern "C" cudaError_t bls12_381::BuildPoseidonMerkleTree(
  const bls12_381::scalar_t* leaves,
  bls12_381::scalar_t* digests,
  uint32_t height,
  int arity,
  poseidon::PoseidonConstants<bls12_381::scalar_t>& constants,
  merkle::TreeBuilderConfig& config);

#endif