name: Check Changed Files

on:
  workflow_call:
    outputs:
      docs:
        description: "Flag for if docs files changed"
        value: ${{ jobs.check-changed-files.outputs.docs }}
      examples:
        description: "Flag for if examples files changed"
        value: ${{ jobs.check-changed-files.outputs.examples }}
      any:
        description: "Flag for if any code files changed"
        value: ${{ jobs.check-changed-files.outputs.any }}
      # Cpp specific outputs
      cpp:
        description: "Flag for if C++ code files changed"
        value: ${{ jobs.check-changed-files.outputs.cpp }}
      field:
        description: "Flag for if C++ field files changed"
        value: ${{ jobs.check-changed-files.outputs.field }}
      curve:
        description: "Flag for if C++ curve files changed"
        value: ${{ jobs.check-changed-files.outputs.curve }}
      ring:
        description: "Flag for if C++ ring files changed"
        value: ${{ jobs.check-changed-files.outputs.ring }}
      msm:
        description: "Flag for if C++ msm files changed"
        value: ${{ jobs.check-changed-files.outputs.msm }}
      ntt:
        description: "Flag for if C++ ntt files changed"
        value: ${{ jobs.check-changed-files.outputs.ntt }}
      ecntt:
        description: "Flag for if C++ ecntt files changed"
        value: ${{ jobs.check-changed-files.outputs.ecntt }}
      fri:
        description: "Flag for if C++ fri files changed"
        value: ${{ jobs.check-changed-files.outputs.fri }}
      sumcheck:
        description: "Flag for if C++ sumcheck files changed"
        value: ${{ jobs.check-changed-files.outputs.sumcheck }}
      pairing:
        description: "Flag for if C++ pairing files changed"
        value: ${{ jobs.check-changed-files.outputs.pairing }}
      poseidon:
        description: "Flag for if C++ poseidon files changed"
        value: ${{ jobs.check-changed-files.outputs.poseidon }}
      poseidon2:
        description: "Flag for if C++ poseidon2 files changed"
        value: ${{ jobs.check-changed-files.outputs.poseidon2 }}
      hash:
        description: "Flag for if C++ hash files changed"
        value: ${{ jobs.check-changed-files.outputs.hash }}
      runtime:
        description: "Flag for if C++ runtime files changed"
        value: ${{ jobs.check-changed-files.outputs.runtime }}
      # Rust specific outputs
      rust:
        description: "Flag for if Rust code files changed"
        value: ${{ jobs.check-changed-files.outputs.rust }}
      rust-field:
        description: "Flag for if Rust field files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-field }}
      rust-curve:
        description: "Flag for if Rust curve files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-curve }}
      rust-ring:
        description: "Flag for if Rust ring files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-ring }}
      rust-msm:
        description: "Flag for if Rust msm files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-msm }}
      rust-ntt:
        description: "Flag for if Rust ntt files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-ntt }}
      rust-ecntt:
        description: "Flag for if Rust ecntt files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-ecntt }}
      rust-fri:
        description: "Flag for if Rust fri files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-fri }}
      rust-sumcheck:
        description: "Flag for if Rust sumcheck files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-sumcheck }}
      rust-pairing:
        description: "Flag for if Rust pairing files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-pairing }}
      rust-poseidon:
        description: "Flag for if Rust poseidon files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-poseidon }}
      rust-poseidon2:
        description: "Flag for if Rust poseidon2 files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-poseidon2 }}
      rust-hash:
        description: "Flag for if Rust hash files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-hash }}
      rust-runtime:
        description: "Flag for if Rust runtime files changed"
        value: ${{ jobs.check-changed-files.outputs.rust-runtime }}
      # Go specific outputs
      go:
        description: "Flag for if Go code files changed"
        value: ${{ jobs.check-changed-files.outputs.go }}
      go-field:
        description: "Flag for if Go field files changed"
        value: ${{ jobs.check-changed-files.outputs.go-field }}
      go-curve:
        description: "Flag for if Go curve files changed"
        value: ${{ jobs.check-changed-files.outputs.go-curve }}
      go-ring:
        description: "Flag for if Go ring files changed"
        value: ${{ jobs.check-changed-files.outputs.go-ring }}
      go-msm:
        description: "Flag for if Go msm files changed"
        value: ${{ jobs.check-changed-files.outputs.go-msm }}
      go-ntt:
        description: "Flag for if Go ntt files changed"
        value: ${{ jobs.check-changed-files.outputs.go-ntt }}
      go-ecntt:
        description: "Flag for if Go ecntt files changed"
        value: ${{ jobs.check-changed-files.outputs.go-ecntt }}
      go-fri:
        description: "Flag for if Go fri files changed"
        value: ${{ jobs.check-changed-files.outputs.go-fri }}
      go-sumcheck:
        description: "Flag for if Go sumcheck files changed"
        value: ${{ jobs.check-changed-files.outputs.go-sumcheck }}
      go-pairing:
        description: "Flag for if Go pairing files changed"
        value: ${{ jobs.check-changed-files.outputs.go-pairing }}
      go-poseidon:
        description: "Flag for if Go poseidon files changed"
        value: ${{ jobs.check-changed-files.outputs.go-poseidon }}
      go-poseidon2:
        description: "Flag for if Go poseidon2 files changed"
        value: ${{ jobs.check-changed-files.outputs.go-poseidon2 }}
      go-hash:
        description: "Flag for if Go hash files changed"
        value: ${{ jobs.check-changed-files.outputs.go-hash }}
      go-runtime:
        description: "Flag for if Go runtime files changed"
        value: ${{ jobs.check-changed-files.outputs.go-runtime }}

jobs:
  check-changed-files:
    name: Check Changed Files
    runs-on: ubuntu-22.04
    outputs:
      docs: ${{ steps.changed_files.outputs.docs }}
      examples: ${{ steps.changed_files.outputs.examples }}
      any: ${{ steps.changed_files.outputs.any }}
      # Feature-specific outputs
      cpp: ${{ steps.changed_files.outputs.cpp }}
      field: ${{ steps.changed_files.outputs.field }}
      curve: ${{ steps.changed_files.outputs.curve }}
      ring: ${{ steps.changed_files.outputs.ring }}
      msm: ${{ steps.changed_files.outputs.msm }}
      ntt: ${{ steps.changed_files.outputs.ntt }}
      ecntt: ${{ steps.changed_files.outputs.ecntt }}
      fri: ${{ steps.changed_files.outputs.fri }}
      sumcheck: ${{ steps.changed_files.outputs.sumcheck }}
      pairing: ${{ steps.changed_files.outputs.pairing }}
      poseidon: ${{ steps.changed_files.outputs.poseidon }}
      poseidon2: ${{ steps.changed_files.outputs.poseidon2 }}
      hash: ${{ steps.changed_files.outputs.hash }}
      runtime: ${{ steps.changed_files.outputs.runtime }}
      # Rust specific outputs
      rust: ${{ steps.changed_files.outputs.rust }}
      rust-field: ${{ steps.changed_files.outputs.rust-field }}
      rust-curve: ${{ steps.changed_files.outputs.rust-curve }}
      rust-ring: ${{ steps.changed_files.outputs.rust-ring }}
      rust-msm: ${{ steps.changed_files.outputs.rust-msm }}
      rust-ntt: ${{ steps.changed_files.outputs.rust-ntt }}
      rust-ecntt: ${{ steps.changed_files.outputs.rust-ecntt }}
      rust-fri: ${{ steps.changed_files.outputs.rust-fri }}
      rust-sumcheck: ${{ steps.changed_files.outputs.rust-sumcheck }}
      rust-pairing: ${{ steps.changed_files.outputs.rust-pairing }}
      rust-poseidon: ${{ steps.changed_files.outputs.rust-poseidon }}
      rust-poseidon2: ${{ steps.changed_files.outputs.rust-poseidon2 }}
      rust-hash: ${{ steps.changed_files.outputs.rust-hash }}
      rust-runtime: ${{ steps.changed_files.outputs.rust-runtime }}
      # Go specific outputs
      go: ${{ steps.changed_files.outputs.go }}
      go-field: ${{ steps.changed_files.outputs.go-field }}
      go-curve: ${{ steps.changed_files.outputs.go-curve }}
      go-ring: ${{ steps.changed_files.outputs.go-ring }}
      go-msm: ${{ steps.changed_files.outputs.go-msm }}
      go-ntt: ${{ steps.changed_files.outputs.go-ntt }}
      go-ecntt: ${{ steps.changed_files.outputs.go-ecntt }}
      go-fri: ${{ steps.changed_files.outputs.go-fri }}
      go-sumcheck: ${{ steps.changed_files.outputs.go-sumcheck }}
      go-pairing: ${{ steps.changed_files.outputs.go-pairing }}
      go-poseidon: ${{ steps.changed_files.outputs.go-poseidon }}
      go-poseidon2: ${{ steps.changed_files.outputs.go-poseidon2 }}
      go-hash: ${{ steps.changed_files.outputs.go-hash }}
      go-runtime: ${{ steps.changed_files.outputs.go-runtime }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Get all changed files
      id: changed-files-yaml
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
      # https://github.com/tj-actions/changed-files#input_files_yaml_from_source_file
      with:
        files_yaml_from_source_file: .github/changed-files.yml
    - name: Run Changed Files script
      id: changed_files
      # https://github.com/tj-actions/changed-files#outputs-
      run: |
        echo "docs=${{ steps.changed-files-yaml.outputs.docs_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "examples=${{ steps.changed-files-yaml.outputs.examples_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "any=${{ steps.changed-files-yaml.outputs.any_any_modified }}" >> "$GITHUB_OUTPUT"

        echo "cpp=${{ steps.changed-files-yaml.outputs.cpp_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "field=${{ steps.changed-files-yaml.outputs.field_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "curve=${{ steps.changed-files-yaml.outputs.curve_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "ring=${{ steps.changed-files-yaml.outputs.ring_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "msm=${{ steps.changed-files-yaml.outputs.msm_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "ntt=${{ steps.changed-files-yaml.outputs.ntt_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "ecntt=${{ steps.changed-files-yaml.outputs.ecntt_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "fri=${{ steps.changed-files-yaml.outputs.fri_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "sumcheck=${{ steps.changed-files-yaml.outputs.sumcheck_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "pairing=${{ steps.changed-files-yaml.outputs.pairing_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "poseidon=${{ steps.changed-files-yaml.outputs.poseidon_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "poseidon2=${{ steps.changed-files-yaml.outputs.poseidon2_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "hash=${{ steps.changed-files-yaml.outputs.hash_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "runtime=${{ steps.changed-files-yaml.outputs.runtime_any_modified }}" >> "$GITHUB_OUTPUT"

        echo "rust=${{ steps.changed-files-yaml.outputs.rust_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-field=${{ steps.changed-files-yaml.outputs.rust-field_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-curve=${{ steps.changed-files-yaml.outputs.rust-curve_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-ring=${{ steps.changed-files-yaml.outputs.rust-ring_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-msm=${{ steps.changed-files-yaml.outputs.rust-msm_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-ntt=${{ steps.changed-files-yaml.outputs.rust-ntt_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-ecntt=${{ steps.changed-files-yaml.outputs.rust-ecntt_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-fri=${{ steps.changed-files-yaml.outputs.rust-fri_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-sumcheck=${{ steps.changed-files-yaml.outputs.rust-sumcheck_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-pairing=${{ steps.changed-files-yaml.outputs.rust-pairing_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-poseidon=${{ steps.changed-files-yaml.outputs.rust-poseidon_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-poseidon2=${{ steps.changed-files-yaml.outputs.rust-poseidon2_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-hash=${{ steps.changed-files-yaml.outputs.rust-hash_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust-runtime=${{ steps.changed-files-yaml.outputs.rust-runtime_any_modified }}" >> "$GITHUB_OUTPUT"

        echo "go=${{ steps.changed-files-yaml.outputs.go_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-field=${{ steps.changed-files-yaml.outputs.go-field_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-curve=${{ steps.changed-files-yaml.outputs.go-curve_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-ring=${{ steps.changed-files-yaml.outputs.go-ring_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-msm=${{ steps.changed-files-yaml.outputs.go-msm_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-ntt=${{ steps.changed-files-yaml.outputs.go-ntt_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-ecntt=${{ steps.changed-files-yaml.outputs.go-ecntt_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-fri=${{ steps.changed-files-yaml.outputs.go-fri_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-sumcheck=${{ steps.changed-files-yaml.outputs.go-sumcheck_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-pairing=${{ steps.changed-files-yaml.outputs.go-pairing_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-poseidon=${{ steps.changed-files-yaml.outputs.go-poseidon_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-poseidon2=${{ steps.changed-files-yaml.outputs.go-poseidon2_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-hash=${{ steps.changed-files-yaml.outputs.go-hash_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go-runtime=${{ steps.changed-files-yaml.outputs.go-runtime_any_modified }}" >> "$GITHUB_OUTPUT"
