name: Check Changed Files

on:
  workflow_call:
    outputs:
      docs:
        description: "Flag for if docs files changed"
        value: ${{ jobs.check-changed-files.outputs.docs }}
      examples:
        description: "Flag for if examples files changed"
        value: ${{ jobs.check-changed-files.outputs.examples }}
      # Any code files changed
      any:
        description: "Flag for if any code files changed"
        value: ${{ jobs.check-changed-files.outputs.any }}
      backend-api:
        description: "Flag for if backend API files changed"
        value: ${{ jobs.check-changed-files.outputs.backend-api }}
      cpp:
        description: "Flag for if C++ code files changed"
        value: ${{ jobs.check-changed-files.outputs.cpp }}
      rust:
        description: "Flag for if Rust code files changed"
        value: ${{ jobs.check-changed-files.outputs.rust }}
      go:
        description: "Flag for if Go code files changed"
        value: ${{ jobs.check-changed-files.outputs.go }}
      cpu-backend:
        description: "Flag for if CPU backend files changed"
        value: ${{ jobs.check-changed-files.outputs.cpu-backend }}
      runtime:
        description: "Flag for if C++ runtime files changed"
        value: ${{ jobs.check-changed-files.outputs.runtime }}
      # Feature specific outputs
      msm:
        description: "Flag for if any (C++, Rust, Go) msm files changed"
        value: ${{ jobs.check-changed-files.outputs.msm }}
      ntt:
        description: "Flag for if any (C++, Rust, Go) ntt files changed"
        value: ${{ jobs.check-changed-files.outputs.ntt }}
      ecntt:
        description: "Flag for if any (C++, Rust, Go) ecntt files changed"
        value: ${{ jobs.check-changed-files.outputs.ecntt }}
      fri:
        description: "Flag for if any (C++, Rust, Go) fri files changed"
        value: ${{ jobs.check-changed-files.outputs.fri }}
      sumcheck:
        description: "Flag for if any (C++, Rust, Go) sumcheck files changed"
        value: ${{ jobs.check-changed-files.outputs.sumcheck }}
      pairing:
        description: "Flag for if any (C++, Rust, Go) pairing files changed"
        value: ${{ jobs.check-changed-files.outputs.pairing }}
      poseidon:
        description: "Flag for if any (C++, Rust, Go) poseidon files changed"
        value: ${{ jobs.check-changed-files.outputs.poseidon }}
      poseidon2:
        description: "Flag for if any (C++, Rust, Go) poseidon2 files changed"
        value: ${{ jobs.check-changed-files.outputs.poseidon2 }}
      hash:
        description: "Flag for if any (C++, Rust, Go) hash files changed"
        value: ${{ jobs.check-changed-files.outputs.hash }}

jobs:
  check-changed-files:
    name: Check Changed Files
    runs-on: ubuntu-22.04
    outputs:
      docs: ${{ steps.changed_files.outputs.docs }}
      examples: ${{ steps.changed_files.outputs.examples }}
      
      any: ${{ steps.changed_files.outputs.any }}
      backend-api: ${{ steps.changed_files.outputs.backend-api }}
      cpp: ${{ steps.changed_files.outputs.cpp }}
      rust: ${{ steps.changed_files.outputs.rust }}
      go: ${{ steps.changed_files.outputs.go }}
      cpu-backend: ${{ steps.changed_files.outputs.cpu-backend }}
      runtime: ${{ steps.changed_files.outputs.runtime }}

      msm: ${{ steps.changed_files.outputs.msm }}
      ntt: ${{ steps.changed_files.outputs.ntt }}
      ecntt: ${{ steps.changed_files.outputs.ecntt }}
      fri: ${{ steps.changed_files.outputs.fri }}
      sumcheck: ${{ steps.changed_files.outputs.sumcheck }}
      pairing: ${{ steps.changed_files.outputs.pairing }}
      poseidon: ${{ steps.changed_files.outputs.poseidon }}
      poseidon2: ${{ steps.changed_files.outputs.poseidon2 }}
      hash: ${{ steps.changed_files.outputs.hash }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Get all changed files
      id: changed-files-yaml
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
      # https://github.com/tj-actions/changed-files#input_files_yaml_from_source_file
      with:
        files_yaml_from_source_file: .github/changed-files.yml
    - name: Run Changed Files script
      id: changed_files
      # https://github.com/tj-actions/changed-files#outputs-
      run: |
        echo "docs=${{ steps.changed-files-yaml.outputs.docs_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "examples=${{ steps.changed-files-yaml.outputs.examples_any_modified }}" >> "$GITHUB_OUTPUT"

        echo "any=${{ steps.changed-files-yaml.outputs.any_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "backend-api=${{ steps.changed-files-yaml.outputs.backend-api_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "cpp=${{ steps.changed-files-yaml.outputs.cpp_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust=${{ steps.changed-files-yaml.outputs.rust_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "go=${{ steps.changed-files-yaml.outputs.go_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "cpu-backend=${{ steps.changed-files-yaml.outputs.cpu-backend_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "runtime=${{ steps.changed-files-yaml.outputs.runtime_any_modified }}" >> "$GITHUB_OUTPUT"
        
        echo "msm=${{ steps.changed-files-yaml.outputs.msm_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "ntt=${{ steps.changed-files-yaml.outputs.ntt_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "ecntt=${{ steps.changed-files-yaml.outputs.ecntt_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "fri=${{ steps.changed-files-yaml.outputs.fri_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "sumcheck=${{ steps.changed-files-yaml.outputs.sumcheck_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "pairing=${{ steps.changed-files-yaml.outputs.pairing_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "poseidon=${{ steps.changed-files-yaml.outputs.poseidon_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "poseidon2=${{ steps.changed-files-yaml.outputs.poseidon2_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "hash=${{ steps.changed-files-yaml.outputs.hash_any_modified }}" >> "$GITHUB_OUTPUT"
