name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-conditional-testing:
    name: Check Conditional Testing
    runs-on: ubuntu-latest
    outputs:
      conditional-testing: ${{ steps.conditional-testing.outputs.conditional-testing }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 5
      - name: Calculate conditions
        id: conditional-testing
        run: |
          COMMIT_MSG=$(git log ${{ github.event.pull_request.head.sha }} -1 --pretty=format:"%s")
          echo "COMMIT_MSG: $COMMIT_MSG"
          COMMIT_MSG_LOWER=$(echo "$COMMIT_MSG" | tr '[:upper:]' '[:lower:]')
          echo "COMMIT_MSG_LOWER: $COMMIT_MSG_LOWER"
          if [[ "$COMMIT_MSG_LOWER" == *"[full ci]"* ]]; then
            CONDITIONAL_TESTING=false
            echo "CONDITIONAL_TESTING=$CONDITIONAL_TESTING"
            echo "conditional-testing=$CONDITIONAL_TESTING" >> $GITHUB_OUTPUT
          else
            CONDITIONAL_TESTING=true
            echo "CONDITIONAL_TESTING=$CONDITIONAL_TESTING"
            echo "conditional-testing=$CONDITIONAL_TESTING" >> $GITHUB_OUTPUT
          fi

  spelling-checker:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: codespell-project/actions-codespell@fad9339798e1ee3fe979ae0a022c931786a408b8
        with:
          # https://github.com/codespell-project/actions-codespell?tab=readme-ov-file#parameter-skip
          skip: ./**/target,./**/build,./docs/*.js,./docs/*.json,./*.svg
          # https://github.com/codespell-project/actions-codespell?tab=readme-ov-file#parameter-ignore_words_file
          ignore_words_file: .codespellignore

  check-changed-files:
    uses: ./.github/workflows/check-changed-files.yml

  check-format:
    name: Check Code Format
    runs-on: [self-hosted, Linux, X64, formatter]
    needs: [check-changed-files]
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Setup go
      if: needs.check-changed-files.outputs.go == 'true'
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
      with:
        go-version: '1.22.0'
        cache: false
    - name: Check clang-format
      if: needs.check-changed-files.outputs.cpp == 'true'
      run: |
        clang-format --version
        ./scripts/format_all.sh . --check --exclude "build|wrappers"
    - name: Check gofmt
      if: needs.check-changed-files.outputs.go == 'true'
      run: if [[ $(go list ./... | xargs go fmt) ]]; then echo "Please run go fmt"; exit 1; fi
    - name: Check rustfmt
      if: needs.check-changed-files.outputs.rust == 'true'
      working-directory: ./wrappers/rust
      run: |
        rustup override set nightly
        cargo fmt --all -- --check

  extract-cuda-backend-branch:
    uses: ./.github/workflows/extract-backend.yml
    with:
      pr-number: ${{ github.event.pull_request.number }}
      backend-type: cuda

  # extract-metal-backend-branch:
  #   uses: ./.github/workflows/extract-backend.yml
  #   with:
  #     pr-number: ${{ github.event.pull_request.number }}
  #     backend-type: metal
  
  test-curve:
    name: Curves
    needs: [check-changed-files, check-format, extract-cuda-backend-branch]
    uses: ./.github/workflows/test-curve.yml
    with:
      backend: ${{ matrix.backend }}
      backend_upper: ${{ matrix.backend_upper }}
      runner: ${{ matrix.runner }}
      backend_branch: ${{ matrix.backend_branch }}
      skip-rust-all-curves: ${{ matrix.skip-rust-all-curves }}
      skip-cpp-all-curves: ${{ matrix.skip-cpp-all-curves }}
      skip-golang-all-curves: ${{ matrix.skip-golang-all-curves }}
      initial-support: ${{ matrix.initial-support }}
      enable_conditional_testing: ${{ needs.check-conditional-testing.outputs.conditional-testing == 'true' }}
      # Changed files flags
      changed_curve: ${{ needs.check-changed-files.outputs.curve }}
      changed_cpp: ${{ needs.check-changed-files.outputs.cpp }}
      changed_rust: ${{ needs.check-changed-files.outputs.rust }}
      changed_go: ${{ needs.check-changed-files.outputs.go }}
      changed_cpu_backend: ${{ needs.check-changed-files.outputs.cpu-backend }}
      changed_backend_api: ${{ needs.check-changed-files.outputs.backend-api }}
      # Feature change flags
      changed_msm: ${{ needs.check-changed-files.outputs.msm }}
      changed_ntt: ${{ needs.check-changed-files.outputs.ntt }}
      changed_ecntt: ${{ needs.check-changed-files.outputs.ecntt }}
      changed_pairing: ${{ needs.check-changed-files.outputs.pairing }}
      changed_fri: ${{ needs.check-changed-files.outputs.fri }}
      changed_sumcheck: ${{ needs.check-changed-files.outputs.sumcheck }}
      changed_poseidon: ${{ needs.check-changed-files.outputs.poseidon }}
      changed_poseidon2: ${{ needs.check-changed-files.outputs.poseidon2 }}
    secrets:
      backend_ssh_key: ${{ secrets[matrix.secret_key] }}
    strategy:
      matrix:
        backend: [cuda]
        # backend: [cuda, metal]
        include:
          - backend: cuda
            backend_upper: CUDA
            secret_key: CUDA_PULL_KEY
            runner: '["self-hosted", "Linux", "X64", "icicle"]'
            backend_branch: ${{ needs.extract-cuda-backend-branch.outputs.backend-branch }}
            skip-rust-all-curves: ""
            skip-cpp-all-curves: ""
            skip-golang-all-curves: "false"
            initial-support: false
          # - backend: metal
          #   backend_upper: METAL
          #   secret_key: METAL_PULL_KEY
          #   runner: '["self-hosted", "macOS", "ARM64", "icicle", "metal"]'
          #   backend_branch: ${{ needs.extract-metal-backend-branch.outputs.backend-branch }}
          #   skip-rust-all-curves: "--skip montgomery --skip ntt --skip poseidon --skip ecntt --skip sumcheck --skip program --skip msm_batch_not_shared --skip msm_skewed_distributions --skip vec_ops_scalars_inv --skip pairing --skip fri"
          #   skip-cpp-all-curves: ".*G2.*|.*ecntt.*|.*ProgramExecutorVecOp.*|.*Sumcheck.*|.*Fri.*|FieldTestBase.polynomialDivision|.*MerkleTree.*|.*poseidon.*|HashApiTest.KeccakLarge"
          #   skip-golang-all-curves: "true"
          #   initial-support: true
          #   supported_features: '["msm"]' # TODO: Since Metal doesn't support all features, we need to specify the supported features

  test-field:
    name: Fields
    needs: [check-changed-files, check-format, extract-cuda-backend-branch]
    uses: ./.github/workflows/test-field.yml
    with:
      backend: ${{ matrix.backend }}
      backend_upper: ${{ matrix.backend_upper }}
      runner: ${{ matrix.runner }}
      backend_branch: ${{ matrix.backend_branch }}
      skip-rust-all-fields: ${{ matrix.skip-rust-all-fields }}
      skip-cpp-all-fields: ${{ matrix.skip-cpp-all-fields }}
      skip-golang-all-fields: ${{ matrix.skip-golang-all-fields }}
      initial-support: ${{ matrix.initial-support }}
      enable_conditional_testing: ${{ needs.check-conditional-testing.outputs.conditional-testing == 'true' }}
      # Changed files flags
      changed_field: ${{ needs.check-changed-files.outputs.field }}
      changed_cpp: ${{ needs.check-changed-files.outputs.cpp }}
      changed_rust: ${{ needs.check-changed-files.outputs.rust }}
      changed_go: ${{ needs.check-changed-files.outputs.go }}
      changed_cpu_backend: ${{ needs.check-changed-files.outputs.cpu-backend }}
      changed_backend_api: ${{ needs.check-changed-files.outputs.backend-api }}
      # Feature change flags
      changed_ntt: ${{ needs.check-changed-files.outputs.ntt }}
      changed_fri: ${{ needs.check-changed-files.outputs.fri }}
      changed_sumcheck: ${{ needs.check-changed-files.outputs.sumcheck }}
      changed_poseidon: ${{ needs.check-changed-files.outputs.poseidon }}
      changed_poseidon2: ${{ needs.check-changed-files.outputs.poseidon2 }}
    secrets:
      backend_ssh_key: ${{ secrets[matrix.secret_key] }}
    strategy:
      matrix:
        backend: [cuda]
        # backend: [cuda, metal]
        include:
          - backend: cuda
            backend_upper: CUDA
            secret_key: CUDA_PULL_KEY
            runner: '["self-hosted", "Linux", "X64", "icicle"]'
            backend_branch: ${{ needs.extract-cuda-backend-branch.outputs.backend-branch }}
            skip-rust-all-curves: ""
            skip-cpp-all-curves: ""
            skip-golang-all-curves: "false"
            initial-support: false
          # - backend: metal
          #   backend_upper: METAL
          #   secret_key: METAL_PULL_KEY
          #   runner: '["self-hosted", "macOS", "ARM64", "icicle", "metal"]'
          #   backend_branch: ${{ needs.extract-metal-backend-branch.outputs.backend-branch }}
          #   skip-rust-all-curves: "--skip montgomery --skip ntt --skip poseidon --skip ecntt --skip sumcheck --skip program --skip msm_batch_not_shared --skip msm_skewed_distributions --skip vec_ops_scalars_inv --skip pairing --skip fri"
          #   skip-cpp-all-curves: ".*G2.*|.*ecntt.*|.*ProgramExecutorVecOp.*|.*Sumcheck.*|.*Fri.*|FieldTestBase.polynomialDivision|.*MerkleTree.*|.*poseidon.*|HashApiTest.KeccakLarge"
          #   skip-golang-all-curves: "true"
          #   initial-support: true
          #   supported_features: '["msm"]'

  test-hash:
    name: Hashes
    needs: [check-changed-files, check-format, extract-cuda-backend-branch]
    uses: ./.github/workflows/test-hash.yml
    with:
      backend: ${{ matrix.backend }}
      backend_upper: ${{ matrix.backend_upper }}
      runner: ${{ matrix.runner }}
      backend_branch: ${{ matrix.backend_branch }}
      skip-rust: ${{ matrix.skip-rust }}
      skip-cpp: ${{ matrix.skip-cpp }}
      skip-golang: ${{ matrix.skip-golang }}
      initial-support: ${{ matrix.initial-support }}
      enable_conditional_testing: ${{ needs.check-conditional-testing.outputs.conditional-testing == 'true' }}
      # Changed files flags
      changed_hash: ${{ needs.check-changed-files.outputs.hash }}
      changed_cpp: ${{ needs.check-changed-files.outputs.cpp }}
      changed_rust: ${{ needs.check-changed-files.outputs.rust }}
      changed_go: ${{ needs.check-changed-files.outputs.go }}
      changed_cpu_backend: ${{ needs.check-changed-files.outputs.cpu-backend }}
      changed_backend_api: ${{ needs.check-changed-files.outputs.backend-api }}
    secrets:
      backend_ssh_key: ${{ secrets[matrix.secret_key] }}
    strategy:
      matrix:
        backend: [cuda]
        # backend: [cuda, metal]
        include:
          - backend: cuda
            backend_upper: CUDA
            secret_key: CUDA_PULL_KEY
            runner: '["self-hosted", "Linux", "X64", "icicle"]'
            backend_branch: ${{ needs.extract-cuda-backend-branch.outputs.backend-branch }}
            skip-rust: ""
            skip-cpp: ""
            skip-golang: "false"
            initial-support: false
          # - backend: metal
          #   backend_upper: METAL
          #   secret_key: METAL_PULL_KEY
          #   runner: '["self-hosted", "macOS", "ARM64", "icicle", "metal"]'
          #   backend_branch: ${{ needs.extract-metal-backend-branch.outputs.backend-branch }}
          #   skip-rust: ""
          #   skip-cpp: ""
          #   skip-golang: "true"
          #   initial-support: true

  test-ring:
    name: Rings
    needs: [check-changed-files, check-format, extract-cuda-backend-branch]
    uses: ./.github/workflows/test-ring.yml
    with:
      backend: ${{ matrix.backend }}
      backend_upper: ${{ matrix.backend_upper }}
      runner: ${{ matrix.runner }}
      backend_branch: ${{ matrix.backend_branch }}
      initial-support: ${{ matrix.initial-support }}
      enable_conditional_testing: ${{ needs.check-conditional-testing.outputs.conditional-testing == 'true' }}
      # Changed files flags
      changed_ring: ${{ needs.check-changed-files.outputs.ring }}
      changed_cpp: ${{ needs.check-changed-files.outputs.cpp }}
      changed_rust: ${{ needs.check-changed-files.outputs.rust }}
      changed_cpu_backend: ${{ needs.check-changed-files.outputs.cpu-backend }}
      changed_backend_api: ${{ needs.check-changed-files.outputs.backend-api }}
      changed_ntt: ${{ needs.check-changed-files.outputs.ntt }}
    secrets:
      backend_ssh_key: ${{ secrets[matrix.secret_key] }}
    strategy:
      matrix:
        backend: [cuda]
        # backend: [cuda, metal]
        include:
          - backend: cuda
            backend_upper: CUDA
            secret_key: CUDA_PULL_KEY
            runner: '["self-hosted", "Linux", "X64", "icicle"]'
            backend_branch: ${{ needs.extract-cuda-backend-branch.outputs.backend-branch }}
            initial-support: false
          # - backend: metal
          #   backend_upper: METAL
          #   secret_key: METAL_PULL_KEY
          #   runner: '["self-hosted", "macOS", "ARM64", "icicle", "metal"]'
          #   backend_branch: ${{ needs.extract-metal-backend-branch.outputs.backend-branch }}
          #   initial-support: true

  test-runtime:
    name: Runtime
    needs: [check-changed-files, check-format, extract-cuda-backend-branch]
    uses: ./.github/workflows/test-runtime.yml
    with:
      backend: ${{ matrix.backend }}
      backend_upper: ${{ matrix.backend_upper }}
      runner: ${{ matrix.runner }}
      backend_branch: ${{ matrix.backend_branch }}
      initial-support: ${{ matrix.initial-support }}
      enable_conditional_testing: ${{ needs.check-conditional-testing.outputs.conditional-testing == 'true' }}
      # Changed files flags
      changed_runtime: ${{ needs.check-changed-files.outputs.runtime }}
      changed_cpp: ${{ needs.check-changed-files.outputs.cpp }}
      changed_rust: ${{ needs.check-changed-files.outputs.rust }}
      changed_go: ${{ needs.check-changed-files.outputs.go }}
      changed_cpu_backend: ${{ needs.check-changed-files.outputs.cpu-backend }}
    secrets:
      backend_ssh_key: ${{ secrets[matrix.secret_key] }}
    strategy:
      matrix:
        backend: [cuda]
        # backend: [cuda, metal]
        include:
          - backend: cuda
            backend_upper: CUDA
            secret_key: CUDA_PULL_KEY
            runner: '["self-hosted", "Linux", "X64", "icicle"]'
            backend_branch: ${{ needs.extract-cuda-backend-branch.outputs.backend-branch }}
            initial-support: false
          # - backend: metal
          #   backend_upper: METAL
          #   secret_key: METAL_PULL_KEY
          #   runner: '["self-hosted", "macOS", "ARM64", "icicle", "metal"]'
          #   backend_branch: ${{ needs.extract-metal-backend-branch.outputs.backend-branch }}
          #   initial-support: true

  test-pqc:
    name: PQC ML-KEM
    needs: [check-changed-files, check-format, extract-cuda-backend-branch]
    uses: ./.github/workflows/test-pqc.yml
    with:
      runner: '["self-hosted", "Linux", "X64", "icicle"]'
      enable_conditional_testing: ${{ needs.check-conditional-testing.outputs.conditional-testing == 'true' }}
      # Changed files flags
      changed_pqc: ${{ needs.check-changed-files.outputs.pqc }}
      changed_cpp: ${{ needs.check-changed-files.outputs.cpp }}
      changed_cpu_backend: ${{ needs.check-changed-files.outputs.cpu-backend }}
      changed_backend_api: ${{ needs.check-changed-files.outputs.backend-api }}
