name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-docs.yml
    with:
      artifact_name: docs-website-artifact-${{ github.sha }}

  deploy:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Download build artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: docs-website-artifact-${{ github.sha }}
          path: ./docs/build

      - name: Copy CNAME to build directory
        run: echo "dev.ingonyama.com" > ./build/CNAME
        working-directory: ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
