name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/*'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'repo'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./repo/docs/package-lock.json

      - name: Install dependencies
        run: npm install --frozen-lockfile
        working-directory: ./repo/docs

      - name: Build website
        run: npm run build
        working-directory: ./repo/docs

      - name: Copy CNAME to build directory
        run: echo "dev.ingonyama.com" > ./build/CNAME
        working-directory: ./repo/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo/docs/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          working-directory: ./repo/docs
