name: Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  ARCH_TYPE: native

jobs:
  check-changed-files:
    name: Check Changed Files
    runs-on: ubuntu-22.04
    outputs:
      golang: ${{ steps.changed_files.outputs.golang }}
      rust: ${{ steps.changed_files.outputs.rust }}
      cpp_cuda: ${{ steps.changed_files.outputs.cpp_cuda }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Get all changed files
      id: changed-files-yaml
      uses: tj-actions/changed-files@v39
      # https://github.com/tj-actions/changed-files#input_files_yaml_from_source_file
      with:
        files_yaml_from_source_file: .github/changed-files.yml
    - name: Run Changed Files script
      id: changed_files
      # https://github.com/tj-actions/changed-files#outputs-
      run: |
        echo "golang=${{ steps.changed-files-yaml.outputs.golang_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "rust=${{ steps.changed-files-yaml.outputs.rust_any_modified }}" >> "$GITHUB_OUTPUT"
        echo "cpp_cuda=${{ steps.changed-files-yaml.outputs.cpp_any_modified }}" >> "$GITHUB_OUTPUT"

  test-rust-linux:
    name: Test Rust on Linux
    runs-on: [self-hosted, Linux, X64, icicle]
    needs: check-changed-files
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run Rust Tests
      if: needs.check-changed-files.outputs.rust == 'true' || needs.check-changed-files.outputs.cpp_cuda == 'true'
      run: cargo test --release --verbose -- --test-threads=1

  test-cpp-linux:
    name: Test C++ on Linux
    runs-on: [self-hosted, Linux, X64, icicle]
    needs: check-changed-files
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Build C++
      working-directory: ./icicle
      if: needs.check-changed-files.outputs.cpp_cuda == 'true'
      run: |
        mkdir -p build
        cmake -S . -B build
        cmake --build build
    - name: Run C++ Tests
      working-directory: ./icicle/build
      if: needs.check-changed-files.outputs.cpp_cuda == 'true'
      run: ctest

  test-golang-linux:
    name: Test Golang on Linux
    runs-on: [self-hosted, Linux, X64, icicle]
    needs: check-changed-files
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Build CUDA libs
      working-directory: ./goicicle
      if: needs.check-changed-files.outputs.golang == 'true' || needs.check-changed-files.outputs.cpp_cuda == 'true'
      run: make libbn254.so
    - name: Run Golang Tests
      if: needs.check-changed-files.outputs.golang == 'true' || needs.check-changed-files.outputs.cpp_cuda == 'true'
      run: |
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/goicicle
        go test ./goicicle/curves/bn254 -count=1
      # TODO: Fix tests for bls12377
      # TODO: Fix tests for bls12381
      # run: go test ./goicicle/curves/bn254 ./goicicle/curves/bls12377 ./goicicle/curves/bls12381 -count=1
