name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump rust crate versions, commit, and tag
        working-directory: wrappers/rust
        # https://github.com/pksunkara/cargo-workspaces?tab=readme-ov-file#version
        run: |
          cargo install cargo-workspaces
          cargo workspaces version ${{ inputs.releaseType }} -y --no-individual-tags -m "Bump rust crates' version"
      - name: Create draft release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          gh release create $LATEST_TAG --generate-notes -d --verify-tag -t "Release $LATEST_TAG"
