// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BLS12_377_NTT_API_H
#define BLS12_377_NTT_API_H

#include "fields/snark_fields/bls12_377_scalar.cuh"
#include <cuda_runtime.h>
#include "ntt/ntt.cuh"
#include "gpu-utils/device_context.cuh"

extern "C" cudaError_t bls12_377InitializeDomain(
  bls12_377::scalar_t* primitive_root, device_context::DeviceContext& ctx, bool fast_twiddles_mode);

extern "C" cudaError_t bls12_377NTTCuda(
  const bls12_377::scalar_t* input, int size, NTTDir dir, ntt::NTTConfig<bls12_377::scalar_t>& config, bls12_377::scalar_t* output)

extern "C" cudaError_t bls12_377ReleaseDomain(device_context::DeviceContext& ctx);

#endif