// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: icicle/include/api/gen_c_api.py


#pragma once

#ifndef BLS12_377_NTT_EXT_API_H
#define BLS12_377_NTT_EXT_API_H

#include "fields/snark_fields/bls12_377_scalar.cuh"
#include <cuda_runtime.h>
#include "ntt/ntt.cuh"
#include "gpu-utils/device_context.cuh"

extern "C" cudaError_t bls12_377ExtensionNTTCuda(
  const bls12_377::extension_t* input, int size, NTTDir dir, ntt::NTTConfig<bls12_377::scalar_t>& config, bls12_377::extension_t* output)

#endif